- name: Get Junos configuration
  junos_facts:
    gather_subset:
      - config

- name: Set config_* variables
  set_fact:
    config_current: "{{ ansible_net_config }}"
    config_latest: "{{ lookup('file', '{{backup_path}}{{ inventory_hostname }}-latest.bak', errors='ignore') }}"
